#!/usr/bin/env bash
#vi: ft=bash

export AWS_DEFAULT_REGION=

export AWS_ACCESS_KEY_ID=
export AWS_SECRET_ACCESS_KEY=
export AWS_SESSION_TOKEN=


ssh_key_name=
stack_name='test-stack'


if aws cloudformation describe-stacks --stack-name $stack_name &>/dev/null; then
    cfn_command='update-stack'
    key_value='UsePreviousValue=true'
else
    cfn_command='create-stack'
    key_value="ParameterValue=$ssh_key_name"
fi

set -x
aws cloudformation $cfn_command \
        --capabilities CAPABILITY_IAM \
        --stack-name $stack_name \
        --template-body file://test_stack.yaml \
        --parameters "ParameterKey=KeyName,$key_value"
