Description: Generates test measurement data and redirects data to CloudWatch for monitoring

Resources:
  S3BucketCleanupLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
      - PolicyName: S3BucketAccess
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:DeleteObject
            - s3:ListBucket
            Resource:
            - !GetAtt DataBucket.Arn
            - !Sub '${DataBucket.Arn}/*'

  SiteWiseBatchPutRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      Policies:
      - PolicyName: SiteWiseAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: iotsitewise:BatchPutAssetPropertyValue
            Resource: '*'
      - PolicyName: OnlyCloudFormationManagesLogGroups
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Deny
            Action: logs:CreateLogGroup
            Resource: '*'
      - PolicyName: AllowWriteCloudWatchLogs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
      - PolicyName: CloudWatchMetricsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: cloudwatch:ListTagsForResource
            Resource: '*'

  CloudWatchSenderRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      Policies:
      - PolicyName: CloudWatchMetricsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action: cloudwatch:PutMetricData
            Resource: '*'
      - PolicyName: OnlyCloudFormationManagesLogGroups
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Deny
            Action: logs:CreateLogGroup
            Resource: '*'
      - PolicyName: AllowWriteCloudWatchLogs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'

  BulkImportRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - iot-bifrost.aws.internal
            - iotsitewise.amazonaws.com
          Action: sts:AssumeRole
      Policies:
      - PolicyName: S3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetBucketLocation
            - s3:GetObject
            - s3:ListBucket
            - s3:PutObject
            Resource:
            - !GetAtt DataBucket.Arn
            - !Sub '${DataBucket.Arn}/*'

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DataBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref DataBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Sid: SiteWiseS3Access
          Effect: Allow
          Principal:
            Service:
            - iot-bifrost.aws.internal
            - iotsitewise.amazonaws.com
          Action:
          - s3:GetObject
          - s3:ListBucket
          - s3:PutObject
          Resource:
          - !GetAtt DataBucket.Arn
          - !Sub '${DataBucket.Arn}/*'

  DataBucketCleanup:
    Type: 'Custom::BucketCleanup'
    Properties:
      ServiceToken: !GetAtt S3BucketCleanupLambda.Arn
      BucketName: !Ref DataBucket

  S3BucketCleanupLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt S3BucketCleanupLambdaRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import cfnresponse, boto3
          def handler(event, context):
              try:
                  if event['RequestType'] == 'Delete':
                      bucket_name = event['ResourceProperties']['BucketName']
                      s3 = boto3.resource('s3')
                      bucket = s3.Bucket(bucket_name)
                      bucket.objects.all().delete()
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                cfnresponse.send(event, context, cfnresponse.FAILED, {}, reason=str(e))

  MeasurementGenLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt SiteWiseBatchPutRole.Arn
      Code:
        # Code will be updated with a separate script
        ZipFile: 'def handler(event, context): pass'

  AnomalyMeasurementGenLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt SiteWiseBatchPutRole.Arn
      Code:
        # Code will be updated with a separate script
        ZipFile: 'def handler(event, context): pass'

  CloudWatchSenderLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt CloudWatchSenderRole.Arn
      Code:
        # Code will be updated with a separate script
        ZipFile: 'def handler(event, context): pass'

  CWAlarmSiteWiseSenderLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt SiteWiseBatchPutRole.Arn
      Code:
        # Code will be updated with a separate script
        ZipFile: 'def handler(event, context): pass'

  MeasurementGenLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${MeasurementGenLambda}"
      RetentionInDays: 1

  AnomalyMeasurementGenLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${AnomalyMeasurementGenLambda}"
      RetentionInDays: 1

  CloudWatchSenderLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CloudWatchSenderLambda}"
      RetentionInDays: 1

  CWAlarmSiteWiseSenderLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CWAlarmSiteWiseSenderLambda}"
      RetentionInDays: 1

  MeasurementGenInvokerRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: 'rate(1 minute)'
      State: DISABLED
      Targets:
        - Id: 1
          Arn: !GetAtt MeasurementGenLambda.Arn
        - Id: 2
          Arn: !GetAtt AnomalyMeasurementGenLambda.Arn

  SiteWiseAssetPropertyListenerTopicRule:
    Type: AWS::IoT::TopicRule
    Properties:
      TopicRulePayload:
        Sql: "SELECT * FROM '$aws/sitewise/asset-models/+/assets/+/properties/+'"
        Actions:
          - Lambda:
              FunctionArn: !GetAtt CloudWatchSenderLambda.Arn

  CWALarmMonitoringSNSTopic:
    Type: AWS::SNS::Topic

  CWAlarmMonitoringSNSTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      Protocol: lambda
      TopicArn: !Ref CWALarmMonitoringSNSTopic
      Endpoint: !GetAtt CWAlarmSiteWiseSenderLambda.Arn

  MeasurementGenInvokerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MeasurementGenLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MeasurementGenInvokerRule.Arn

  AnomalyMeasurementGenInvokerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref AnomalyMeasurementGenLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MeasurementGenInvokerRule.Arn

  CloudWatchSenderPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CloudWatchSenderLambda
      Principal: iot.amazonaws.com
      SourceArn: !GetAtt SiteWiseAssetPropertyListenerTopicRule.Arn

  CWAlarmSiteWiseSenderPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref CWAlarmSiteWiseSenderLambda
      Principal: sns.amazonaws.com
      SourceArn: !Ref CWALarmMonitoringSNSTopic

Outputs:
  MeasurementGenInvokerRuleName:
    Value: !Ref MeasurementGenInvokerRule
  MeasurementGenLambdaName:
    Value: !Ref MeasurementGenLambda
  AnomalyMeasurementGenLambdaName:
    Value: !Ref AnomalyMeasurementGenLambda
  CloudWatchSenderLambdaName:
    Value: !Ref CloudWatchSenderLambda
  CWAlarmSiteWiseSenderLambdaName:
    Value: !Ref CWAlarmSiteWiseSenderLambda
  CWALarmMonitoringSNSTopicArn:
    Value: !Ref CWALarmMonitoringSNSTopic
  BucketName:
    Value: !Ref DataBucket
  BulkImportRoleArn:
    Value: !GetAtt BulkImportRole.Arn
