# Used for local testing

handler: loadtest/createmodels.handler

environment_variables:
  DDB_ENDPOINT: 'http://localhost:8000'
  COMPLETED_MODELS_TABLE: 'completed_models'
  MODELS_TABLE: 'models'
  DATA_BUCKET: 'mytestbucket'
  MODELS_FILE_KEY: 'models.json'
