Description: Generates test measurement data for SiteWise Asset Properties

Parameters:
  AssetPropertyIdS3Key:
    Type: String
    Description: The S3 location of the CSV file containing asset and property IDs

Resources:
  S3BucketCleanupLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      ManagedPolicyArns:
      - !Sub "arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
      Policies:
      - PolicyName: S3BucketAccess
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - s3:DeleteObject
            - s3:ListBucket
            Resource:
            - !GetAtt DataBucket.Arn
            - !Sub '${DataBucket.Arn}/*'
      - PolicyName: LetCfnManageLogGroups
        PolicyDocument:
          Statement:
          - Effect: Deny
            Action: logs:CreateLogGroup
            Resource: "*"

  S3BucketCleanupLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.12
      Role: !GetAtt S3BucketCleanupLambdaRole.Arn
      Timeout: 30
      Code:
        ZipFile: |
          import cfnresponse, boto3
          def handler(event, context):
              try:
                  if event['RequestType'] == 'Delete':
                      bucket_name = event['ResourceProperties']['BucketName']
                      s3 = boto3.resource('s3')
                      bucket = s3.Bucket(bucket_name)
                      bucket.objects.all().delete()
                  cfnresponse.send(event, context, cfnresponse.SUCCESS, {})
              except Exception as e:
                cfnresponse.send(event, context, cfnresponse.FAILED, {}, reason=str(e))

  MeasurementGenRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Action: sts:AssumeRole
          Principal:
            Service: lambda.amazonaws.com
      Policies:
      - PolicyName: SiteWiseAccessPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - iotsitewise:BatchPutAssetPropertyValue
              - iotsitewise:BatchGetAssetPropertyValue
            Resource: '*'
      - PolicyName: S3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - s3:GetObject
            Resource:
            - !Sub '${DataBucket.Arn}/*'
      - PolicyName: OnlyCloudFormationManagesLogGroups
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Deny
            Action: logs:CreateLogGroup
            Resource: '*'
      - PolicyName: AllowWriteCloudWatchLogs
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'

  MeasurementGenLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: gen_measurement.handler
      Runtime: python3.12
      Role: !GetAtt MeasurementGenRole.Arn
      Timeout: 30
      Environment:
        Variables:
          DATA_S3_BUCKET: !Ref DataBucket
          ASSET_PROPERTY_ID_S3_KEY: !Ref AssetPropertyIdS3Key
      Code:
        ZipFile: 'def handler(event, context): pass'

  MeasurementGenLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${MeasurementGenLambda}"
      RetentionInDays: 1

  MeasurementGenInvokerRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: 'rate(1 minute)'
      State: DISABLED
      Targets:
      - Id: 1
        Arn: !GetAtt MeasurementGenLambda.Arn

  MeasurementGenInvokerPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref MeasurementGenLambda
      Principal: events.amazonaws.com
      SourceArn: !GetAtt MeasurementGenInvokerRule.Arn

  DataBucket:
    Type: AWS::S3::Bucket
    Properties:
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DataBucketCleanup:
    Type: 'Custom::BucketCleanup'
    Properties:
      ServiceToken: !GetAtt S3BucketCleanupLambda.Arn
      BucketName: !Ref DataBucket

Outputs:
  MeasurementGenInvokerRuleName:
    Value: !Ref MeasurementGenInvokerRule
  MeasurementGenLambdaName:
    Value: !Ref MeasurementGenLambda
  BucketName:
    Value: !Ref DataBucket
