#!/usr/bin/env python3

import time

import boto3
import click
from botocore.exceptions import ClientError


def get_stack_status(cfn_client, stack_name):
    try:
        return cfn_client.describe_stacks(StackName=stack_name)['Stacks'][0]['StackStatus']
    except ClientError:
        return 'DELETED'


@click.command(context_settings={'help_option_names': ['-h', '--help']})
@click.option('-s', '--stack-name', help='CFN Stack Name', required=True)
@click.option('-r', '--region-name', '--region', help='Region name', required=True)
def main(stack_name, region_name):
    """
    Waits for an AWS Cloudformation stack to complete its update process.
    """

    cfn_client = boto3.client('cloudformation', region_name=region_name)
    status = get_stack_status(cfn_client, stack_name)
    print(f'Current status: {status}')
    print(f'Waiting for stack progress to complete...', end='', flush=True)
    while('IN_PROGRESS' in status):
        print('.', end='', flush=True)
        time.sleep(5)
        status = get_stack_status(cfn_client, stack_name)
    print('\nFinal status: {}'.format(status))


if __name__ == '__main__':
    main()
