#!/usr/bin/env python3
# Helper script for whenever you need to convert python dict output to valid json
#
# Usages:
# CLI:
#     dict2json "{'a': 1}"
#     echo "{'a': 1}" | dict2json
#
# Vim:
#     !dict2json

import argparse
import ast
import json
import sys


parser = argparse.ArgumentParser()
parser.add_argument('input', nargs='?')
args = parser.parse_args()

dict_str = args.input if sys.stdin.isatty() else sys.stdin.read().rstrip()
d = ast.literal_eval(dict_str)
print(json.dumps(d, indent=2))
