#!/usr/bin/env python3

import argparse
import uuid


parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
parser.add_argument('-n', '--num', help='Number of UUIDs to generate', type=int, default=1)
args = parser.parse_args()

print('\n'.join(str(uuid.uuid4()) for _ in range(args.num)))
