#!/usr/bin/env python3

import argparse
import sys
from urllib.parse import unquote


parser = argparse.ArgumentParser()
parser.add_argument('input', nargs='?')
args = parser.parse_args()

encoded_str = args.input if sys.stdin.isatty() else sys.stdin.read().rstrip()
print(unquote(encoded_str))
