#!/usr/bin/env python3

import argparse
import sys
from urllib.parse import quote_plus


parser = argparse.ArgumentParser()
parser.add_argument('input', nargs='?')
args = parser.parse_args()

url_str = args.input if sys.stdin.isatty() else sys.stdin.read().rstrip()
print(quote_plus(url_str))
