# File formats
#
# ssh-rsa AAAAB3Nza... user@host        OpenSSH public key (id_rsa.pub)
# -----BEGIN PUBLIC KEY-----            OpenSSL (PKCS#8) public key
# ---- BEGIN SSH2 PUBLIC KEY ----       SSH2 (RFC4716) public key
#
# -----BEGIN OPENSSH PRIVATE KEY-----   OpenSSH private key (id_rsa)
# -----BEGIN PRIVATE KEY-----           OpenSSL (PKCS#8) private key
# -----BEGIN RSA PRIVATE KEY-----       Legacy OpenSSL (PKCS#1) private key
#
#
# Required file permissions
#
# chmod 700 ~/.ssh
#
# chmod 600 ~/.ssh/id_rsa
# chmod 600 ~/.ssh/id_ed25519
#
# chmod 644 ~/.ssh/id_rsa.pub
# chmod 644 ~/.ssh/id_ed25519.pub


# OpenSSL (PKCS#8) public key > OpenSSH
ssh-keygen -i -m PKCS8 -f path/to/openssl.pub > path/to/openssh.pub

# OpenSSH public key > OpenSSL (PKCS#8)
ssh-keygen -e -m PKCS8 -f path/to/openssh.pub > path/to/openssl.pub

# Legacy SSH2 (RFC4716) public key > OpenSSH
ssh-keygen -i -m RFC4716 -f path/to/ssh2.pub > path/to/openssh.pub

# OpenSSH private key > public key
ssh-keygen -y -f path/to/openssh.prv > path/to/openssh.pub

# Legacy OpenSSL (PKCS#1) private key > Modern OpenSSH
ssh-keygen -p -o -f path/to/legacy_id_rsa

# OpenSSL (PKCS#8) private key > OpenSSH
# Modifies the file in-place, make a backup first!
# Prompts for passphrase. Removes it if you hit Enter without typing a new one.
ssh-keygen -p -f path/to/openssl.prv

# OpenSSH private key > OpenSSL (PKCS#8)
# Modifies the file in-place, make a backup first!
# Prompts for passphrase. Removes it if you hit Enter without typing a new one.
ssh-keygen -p -m PKCS8 -f path/to/openssh.prv

# OpenSSL (PKCS#8) private key > Legacy OpenSSL (PKCS#1)
openssl rsa -in path/to/pkcs8.key -traditional -out path/to/legacy_id_rsa

# Calculate fingerprint for OpenSSH public key
ssh-keygen -l -f path/to/openssh.pub

# Calculate fingerprint for Ed25519 public key (New format used by AWS EC2)
ssh-keygen -l -f path/to/id_ed25519.pub

# Calculate fingerprint for RSA key generated by AWS EC2 (SHA-1 Private DER)
openssl pkcs8 -in path/to/aws.pem -inform PEM -outform DER -topk8 -nocrypt | openssl sha1 -c

# Calculate fingerprint for RSA key imported to AWS EC2 (MD5 Public DER)
# Input must be an OpenSSL-compatible private key format (AWS .pem or legacy PKCS#1)
openssl rsa -in path/to/openssl.prv.pem -pubout -outform DER 2>/dev/null | openssl md5 -c

